### PR TITLE
include polly

### PR DESCRIPTION
**Pull request by tyler274**
http://polly.llvm.org/docs/

### CODE REVIEW

**Comment by kerberizer** [comment]
Sorry for having missed that. There seem to be some issues with the build currently--as soon as I fix them (or they resolve on their own), I'll see to have this merged. Thanks for the pull request!

**Comment by tyler274** [comment]
Enabling GPU codegen for polly is probably also a good idea, as for linking polly into tools it came up on the mailing list as a solution to some bugs. 
```
-DPOLLY_ENABLE_GPGPU_CODEGEN:BOOL=ON \
-DLINK_POLLY_INTO_TOOLS:BOOL=ON
```

**Comment by lovesegfault** [comment]
Is there anything I can do to help this get merged @kerberizer?

**Comment by kerberizer** [comment]
@bemeurer, thank you! The truth unfortunately is that my focus has changed significantly over the past year or so. Sorry, indeed, for that awfully long delay.

**Pull request closed without merging**
